language: csharp
solution: TravisTestApp.sln
install:
  - nuget restore TravisTestApp.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release TravisTestApp.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console-exe ./NUnitTestProject/bin/Release/NUnitTestProject.dll