# language: csharp
# solution: TravisTestApp.sln
# install:
#   - nuget restore TravisTestApp/TravisTestApp.sln
#   - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
# script:
#   - msbuild /p:Configuration=Release TravisTestApp/TravisTestApp.sln
#   - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console-exe ./TravisTestApp/NUnitTestProject/bin/Release/NUnitTestProject.dll
language: csharp
mono: none
dotnet: 3.1.404
dist: xenial
install:
 - dotnet restore
script:
 - cd TravisTestApp/NUnitTestProject
 - dotnet test
